# Generated by Django 6.0.1 on 2026-02-23 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '__first__'),
        ('profiles', '0004_travelerprofile_city_travelerprofile_country_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guideprofile',
            name='languages',
        ),
        migrations.AddField(
            model_name='guideprofile',
            name='languages',
            field=models.ManyToManyField(blank=True, related_name='guide_profiles', to='core.language'),
        ),
    ]
