# Generated by Django 6.0.3 on 2026-08-30 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_remove_guideprofile_languages_guideprofile_languages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guideprofile',
            name='verification_status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('verified', 'Verificado'), ('rejected', 'Rechazado')], default='pending', max_length=20),
        ),
    ]
