# Generated by Django 6.0.1 on 2026-02-23 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('es', 'Español'), ('en', 'English'), ('de', 'Deutsch'), ('fr', 'Français'), ('it', 'Italiano'), ('pt', 'Português')], max_length=5, unique=True)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
    ]
