# Generated by Django 6.0.1 on 2026-02-23 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='code',
            field=models.CharField(choices=[('es', 'Español'), ('en', 'English'), ('de', 'Deutsch'), ('fr', 'Français'), ('it', 'Italiano'), ('pt', 'Português'), ('nl', 'Nederlands'), ('sv', 'Svenska'), ('pl', 'Polski'), ('da', 'Dansk'), ('fi', 'Suomi'), ('zh', '中文 (Chinese)')], max_length=5, unique=True),
        ),
    ]
