# Generated by Django 6.0.1 on 2026-02-03 00:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_alter_invoice_seq_alter_invoice_year'),
        ('bookings', '0011_alter_booking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='booking',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoice', to='bookings.booking'),
        ),
    ]
