# Generated by Django 6.0.1 on 2026-02-03 00:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_invoice_booking'),
        ('bookings', '0011_alter_booking_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='booking',
            field=models.OneToOneField(blank=True, help_text='Reserva asociada a esta factura (si aplica).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoice', to='bookings.booking'),
        ),
    ]
