# Generated by Django 6.0.1 on 2026-02-03 02:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_alter_invoice_booking'),
        ('bookings', '0011_alter_booking_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='kind',
            field=models.CharField(choices=[('standard', 'Standard'), ('rectificative', 'Rectificative')], db_index=True, default='standard', max_length=20),
        ),
        migrations.AddField(
            model_name='invoice',
            name='rectification_reason',
            field=models.CharField(blank=True, help_text='Motivo de rectificación (cancelación, cambio de fecha, etc.)', max_length=255),
        ),
        migrations.AddField(
            model_name='invoice',
            name='rectifies',
            field=models.ForeignKey(blank=True, help_text='Factura original que esta factura rectifica (abono/rectificación).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rectifications', to='billing.invoice'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('kind', 'standard'), ('rectifies__isnull', True)), models.Q(('kind', 'rectificative'), ('rectifies__isnull', False)), _connector='OR'), name='invoice_kind_rectifies_consistency'),
        ),
    ]
