# Generated by Django 6.0.3 on 2026-08-30 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_invoice_kind_invoice_rectification_reason_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='kind',
            field=models.CharField(choices=[('standard', 'Ordinaria'), ('rectificative', 'Rectificativa')], db_index=True, default='standard', max_length=20),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('draft', 'Borrador'), ('issued', 'Emitida'), ('void', 'Anulada')], default='draft', max_length=10),
        ),
    ]
