# Generated by Django 6.0.1 on 2026-02-21 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('availability', '0002_experienceavailability_daily_capacity_bookings'),
    ]

    operations = [
        migrations.AddField(
            model_name='experienceavailability',
            name='max_people_per_booking',
            field=models.PositiveIntegerField(blank=True, help_text='Máximo de personas por excursión (reserva). Vacío = sin límite.', null=True),
        ),
    ]
