# Generated by Django 6.0.1 on 2026-02-25 21:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='message',
            name='chat_messag_convers_d0740f_idx',
        ),
        migrations.RemoveIndex(
            model_name='message',
            name='chat_messag_sender__62c9f9_idx',
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['conversation', 'created_at'], name='chat_messag_convers_3154fc_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['sender', 'created_at'], name='chat_messag_sender__b02346_idx'),
        ),
        migrations.AddIndex(
            model_name='participant',
            index=models.Index(fields=['conversation', 'last_read_at'], name='chat_partic_convers_344558_idx'),
        ),
    ]
