# Generated by Django 6.0.3 on 2026-08-30 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_remove_message_chat_messag_convers_d0740f_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='status',
            field=models.CharField(choices=[('active', 'Activa'), ('closed', 'Cerrada'), ('blocked', 'Bloqueada')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='message',
            name='kind',
            field=models.CharField(choices=[('text', 'Texto'), ('system', 'Sistema')], default='text', max_length=20),
        ),
        migrations.AlterField(
            model_name='participant',
            name='role',
            field=models.CharField(choices=[('traveler', 'Viajero'), ('guide', 'Guía')], max_length=20),
        ),
    ]
