# Generated by Django 6.0.1 on 2026-02-21 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experiences', '0004_experience_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='transport_requirement',
            field=models.CharField(choices=[('own_vehicle', 'Vehículo propio'), ('bicycle', 'Bicicleta'), ('on_foot', 'A pie')], default='on_foot', max_length=20),
        ),
    ]
