# Generated by Django 6.0.1 on 2026-02-22 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experiences', '0005_experience_transport_requirement'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'Fácil'), ('moderate', 'Moderada'), ('hard', 'Difícil')], default='easy', max_length=10),
        ),
    ]
