# Generated by Django 6.0.1 on 2026-03-09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("experiences", "0006_experience_difficulty"),
    ]

    operations = [
        migrations.AddField(
            model_name="experience",
            name="country",
            field=models.CharField(blank=True, default="España", max_length=100),
        ),
        migrations.AddField(
            model_name="experience",
            name="region",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
        migrations.AddField(
            model_name="experience",
            name="province",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
        migrations.AddField(
            model_name="experience",
            name="island",
            field=models.CharField(blank=True, db_index=True, default="", max_length=120),
        ),
        migrations.AddField(
            model_name="experience",
            name="city",
            field=models.CharField(blank=True, db_index=True, default="", max_length=120),
        ),
        migrations.AddField(
            model_name="experience",
            name="latitude",
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name="experience",
            name="longitude",
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddIndex(
            model_name="experience",
            index=models.Index(fields=["island", "city"], name="experiences_island_a8cc5d_idx"),
        ),
    ]
