# Generated by Django 5.2.12 on 2026-08-29 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experiences', '0007_experience_structured_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(db_index=True, max_length=5)),
                ('name', models.CharField(max_length=80)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='experiences.category')),
            ],
            options={
                'verbose_name': 'Traducción de categoría',
                'verbose_name_plural': 'Traducciones de categoría',
                'unique_together': {('category', 'language')},
            },
        ),
        migrations.CreateModel(
            name='ExperienceTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(db_index=True, max_length=5)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('is_machine_translated', models.BooleanField(default=True)),
                ('is_outdated', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('experience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='experiences.experience')),
            ],
            options={
                'verbose_name': 'Traducción de experiencia',
                'verbose_name_plural': 'Traducciones de experiencia',
                'unique_together': {('experience', 'language')},
            },
        ),
    ]
