# Generated by Django 6.0.1 on 2026-02-16 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newslettersubscriber',
            name='consent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='newslettersubscriber',
            name='is_official_guide',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='newslettersubscriber',
            name='island',
            field=models.CharField(blank=True, choices=[('lanzarote', 'Lanzarote'), ('fuerteventura', 'Fuerteventura'), ('gran_canaria', 'Gran Canaria'), ('tenerife', 'Tenerife'), ('la_gomera', 'La Gomera'), ('la_palma', 'La Palma'), ('el_hierro', 'El Hierro'), ('la_graciosa', 'La Graciosa'), ('otra', 'Otra / no aplica')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='newslettersubscriber',
            name='region',
            field=models.CharField(blank=True, choices=[('canarias', 'Canarias'), ('peninsula', 'Península'), ('baleares', 'Baleares'), ('extranjero', 'Extranjero'), ('nsnc', 'Prefiero no decirlo')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='newslettersubscriber',
            name='role',
            field=models.CharField(blank=True, choices=[('traveler', 'Viajero'), ('guide', 'Guía'), ('both', 'Ambos'), ('nsnc', 'No lo sé / prefiero no decirlo')], default='', max_length=20),
        ),
    ]
