# Generated by Django 6.0.1 on 2026-02-21 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0011_alter_booking_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='transport_mode',
            field=models.CharField(choices=[('own_vehicle', 'Vehículo propio'), ('bicycle', 'Bicicleta'), ('on_foot', 'A pie'), ('minibus', 'Minibus (legacy)')], default='own_vehicle', max_length=20),
        ),
    ]
