# Generated by Django 6.0.1 on 2026-02-23 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0012_alter_booking_transport_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='preferred_language',
            field=models.CharField(choices=[('', 'Selecciona un idioma'), ('es', 'Español'), ('en', 'English'), ('de', 'Deutsch'), ('fr', 'Français'), ('it', 'Italiano'), ('pt', 'Português')], default='es', max_length=5),
        ),
    ]
