# Generated by Django 6.0.1 on 2026-02-23 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0013_alter_booking_preferred_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='preferred_language',
            field=models.CharField(choices=[('', 'Selecciona un idioma'), ('es', 'Español'), ('en', 'English'), ('de', 'Deutsch'), ('fr', 'Français'), ('it', 'Italiano'), ('pt', 'Português'), ('nl', 'Nederlands'), ('sv', 'Svenska'), ('pl', 'Polski'), ('da', 'Dansk'), ('fi', 'Suomi'), ('zh', '中文 (Chinese)')], default='es', max_length=5),
        ),
    ]
