# Generated by Django 6.0.1 on 2026-02-23 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0014_alter_booking_preferred_language'),
        ('core', '0002_alter_language_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='preferred_language_code',
            field=models.CharField(blank=True, default='', help_text='LEGACY: código anterior (ej: es/en). Solo durante migración.', max_length=5),
        ),
        migrations.AlterField(
            model_name='booking',
            name='preferred_language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='core.language'),
        ),
    ]
