# Generated by Django 6.0.1 on 2026-02-24 00:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0015_booking_preferred_language_code_and_more'),
        ('core', '0002_alter_language_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='preferred_language_code',
        ),
        migrations.AlterField(
            model_name='booking',
            name='preferred_language',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='core.language'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='transport_mode',
            field=models.CharField(choices=[('own_vehicle', 'Vehículo propio'), ('bicycle', 'Bicicleta'), ('on_foot', 'A pie'), ('minibus', 'Minibus')], default='own_vehicle', max_length=20),
        ),
    ]
