# Generated by Django 6.0.3 on 2026-08-30 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0016_remove_booking_preferred_language_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('accepted', 'Aceptada'), ('rejected', 'Rechazada'), ('canceled', 'Cancelada'), ('change_requested', 'Cambio solicitado'), ('cancel_requested', 'Cancelación solicitada')], default='pending', max_length=20),
        ),
    ]
