# Generated by Django 6.0.3 on 2026-08-30 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_remove_review_is_public_review_booking_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('published', 'Publicada'), ('flagged', 'Reportada')], db_index=True, default='pending', max_length=20),
        ),
    ]
